apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      tolerations:
        - key: nodegroup
          operator: Equal
          value: backend
          effect: NoSchedule
      containers:
        - image: nginx
          name: nginx