apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-demo
data:
  virual_host: "vhost1.localhost.com"
  index.html: |
    <html>
    <head>
        <title>ConfigMap Example</title>
    </head>
    <body>
    <h1>ConfigMap Example</h1>
    <p>This is an example of a ConfigMap in Kubernetes.</p>
    </body>
    </html>
  vhost.conf: |
    server {
        listen 80;
        listen [::]:80;
    
        root /usr/share/nginx/app1;
        index index.html index.htm index.nginx-debian.html;
    
        server_name app.localhost.com www.app.localhost.com;

        location / {
            try_files $uri $uri/ =404;
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy: { }
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx
          name: nginx
          resources: { }
          env:
            - name: VIRTUAL_HOST
              valueFrom:
                configMapKeyRef:
                  name: nginx-demo
                  key: virual_host
          volumeMounts:
            - mountPath: /usr/share/nginx/app1/index.html
              subPath: index.html
              name: index-html
            - mountPath: /etc/nginx/conf.d/vhost.conf
              subPath: vhost.conf
              name: vhost
      volumes:
        - name: index-html
          configMap:
            name: nginx-demo
            items:
              - key: index.html
                path: index.html
        - name: vhost
          configMap:
            name: nginx-demo
            items:
              - key: vhost.conf
                path: vhost.conf