apiVersion: v1
kind: Secret
metadata:
  name: credentials
type: kunernetes.io/basic-auth
data:
  username: bWF0ZXVz
  password: bWF0ZXVz
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy: { }
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx
          name: nginx
          resources: { }
          env:
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: password
          volumeMounts:
            - mountPath: /tmp
              name: credentials
              readOnly: true
      volumes:
        - name: credentials
          secret:
            secretName: credentials